@startuml
'https://plantuml.com/activity-diagram-beta

|Customer|
start
:Provide Personal Information;
-[dashed]->
:Customer Details;
|Bank|
-[hidden]->
split
:Check Account Information;



@enduml
